### ISSUE TITLE
v1 is not up to date with the latest version

### ISSUE THREAD

**Issue by tcarmet** [miniscruff/changie-action#112]
Hello @miniscruff 👋 

Recently took the changie-action for a run and stumbled upon the issue mentioned on #82.

I thought I had the correct version of the action as I was using the `v1` tag.
But realized after a while that the `v1` tag has not been updated with the latest release.

### Workaround

Using the `v1.0.1` tag directly fixes the issue.

**Comment by miniscruff** [comment]
Whelp, I guess my action didn't do it properly. Hold please.

**Comment by miniscruff** [comment]
Should be fixed now, will have to come back and see why the action didn't recreate the v1 tag/release like I thought it would.
